# -*- coding: utf-8 -*-
"""Programa de análise meteorológica de 2021 - Fase 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niaA6XGIbcxJNCH-Dl2e9c8M22atUpze
"""

# Programa de análise meteorológica de 2021 Fase 1

# Lista com nomes dos meses para ficar mais claro
meses_extenso = ["janeiro", "fevereiro", "março", "abril", "maio", "junho",
                 "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]

# Lista para armazenar as temperaturas
temperaturas = []

# Coletar as temperaturas para cada mês (1 a 12)
for i in range(12):
    print(f"\nMês {i+1} - {meses_extenso[i]}:")

    # Validar a temperatura e checar
    temp_valida = False
    while not temp_valida:
        temp = input("Digite a temperatura máxima (em Celsius): ")
        try:
            temp = float(temp)
            if -60 <= temp <= 50:
                temp_valida = True
            else:
                print("Erro: A temperatura deve estar entre -60 e 50 graus Celsius!")
        except ValueError:
            print("Erro: Digite um número válido!")

    # Armazenar a temperatura se for válida
    temperaturas.append(temp)

# Calcular a soma das temperaturas
soma_temps = 0
for temp in temperaturas:
    soma_temps = soma_temps + temp
temp_media = soma_temps / 12

# Contar meses escaldantes
meses_escaldantes = 0
for temp in temperaturas:
    if temp > 33:
        meses_escaldantes = meses_escaldantes + 1

# Encontrar maior e menor temperatura
maior_temp = temperaturas[0]
menor_temp = temperaturas[0]
for temp in temperaturas:
    if temp > maior_temp:
        maior_temp = temp
    if temp < menor_temp:
        menor_temp = temp

# Encontrar todos os meses mais escaldantes (se houver mais de um)
meses_mais_quentes = []
for i in range(12):
    if temperaturas[i] == maior_temp:
        meses_mais_quentes.append(i)

# Encontrar todos os meses menos quentes (se houver mais de um)
meses_menos_quentes = []
for i in range(12):
    if temperaturas[i] == menor_temp:
        meses_menos_quentes.append(i)

# Mostrar resultados
print("\n=== Resultados ===")
print(f"Temperatura média máxima anual: {temp_media:.1f}°C")
print(f"Quantidade de meses escaldantes (>33°C): {meses_escaldantes}")

# Mostrar todos os meses mais escaldantes (se houver mais de um)
print("Mês(es) mais escaldante(s): ", end="")
for j in range(len(meses_mais_quentes)):
    if j > 0:
        print(" e ", end="")
    print(f"{meses_extenso[meses_mais_quentes[j]]}", end="")
print(f" ({maior_temp}°C)")

# Mostrar todos os meses menos quentes (se houver mais de um)
print("Mês(es) menos quente(s): ", end="")
for j in range(len(meses_menos_quentes)):
    if j > 0:
        print(" e ", end="")
    print(f"{meses_extenso[meses_menos_quentes[j]]}", end="")
print(f" ({menor_temp}°C)")

# Pausar para evitar que o terminal feche
input("\nPressione Enter para fechar o programa...")